Algoritmo "Exercicio Proposto 03"

// Seção de Declarações das variáveis 
Var
    gasolina,valor,litros:real

// Seção de Comandos, procedimento, funções, operadores, etc... 
Inicio 
    escreva("Digite o preço da gasolina:")
    leia(gasolina)
    escreva("Digite o valor do pagamento:")
    leia(valor)
// Cálculo dos litros de gasolina comprados
    litros<-valor/gasolina
    escreva("Foram colocados ",litros)
    escreva(" de gasolina no tanque")
Fimalgoritmo