// Questão 3

// Analise o código abaixo e escolha os valores correspondentes de A, B e C


Algoritmo "Avaliação Ciclo 1 - Questão 3"

// Seção de Declarações das variáveis 
Var
    A,B,C:real

// Seção de Comandos, procedimento, funções, operadores, etc... 
Inicio
    A<-B+C
    B<-25
    C<-13
    A<-B-A
    C<-C+A
    B<-30-C+B
    escreva("A =",A)
    escreva("B =",B)
    escreva("C =",C)
Fimalgoritmo